# choices.py
GENRE_CHOICES = [
    ('Horror', 'GENRE: Horror: Explores themes of fear, supernatural events, and survival in a frightening setting.'),
    ('Mystery', 'GENRE: Mystery: Centers around solving puzzles, uncovering secrets, and revealing hidden truths.'),
    ('Fantasy', 'GENRE: Fantasy: Features magical elements, mythical creatures, and epic quests in an imagined world.'),
    ('Science Fiction', 'GENRE: Science Fiction: Set in futuristic or speculative settings, exploring advanced technology, space travel, and otherworldly phenomena.'),
    ('Thriller', 'GENRE: Thriller: Focuses on suspense, tension, and excitement, often featuring fast-paced action and cliffhangers.'),
    ('Noir', 'GENRE: Noir: Characterized by its cynical attitude, moral ambiguity, and visual style that emphasizes low-key lighting and unbalanced compositions.'),
    ('Adventure', 'GENRE: Adventure: Involves exploration, travel, and the discovery of unknown territories or experiences.'),
    ('Romance', 'GENRE: Romance: Revolves around love relationships, emotional conflicts, and personal growth.'),
    ('Historical', 'GENRE: Historical: Set in a historically accurate or inspired past, exploring events, settings, or characters from history.'),
    ('Post-Apocalyptic', 'GENRE: Post-Apocalyptic: Deals with life after a catastrophic event, focusing on survival, dystopia, and societal collapse.'),
    ('Cyberpunk', 'GENRE: Cyberpunk: Incorporates high-tech and low-life elements, focusing on advanced technology and systemic decay in a dystopian future.'),
    ('Gothic', 'GENRE: Gothic: Combines horror, romance, and mystery in a setting characterized by its medieval or dark antiquated look.'),
    ('Western', 'GENRE: Western: Set in the American frontier, featuring cowboys, outlaws, and tumultuous law enforcement in the wild west.'),
    ('Supernatural', 'GENRE: Supernatural: Involves fantastical and paranormal elements that are beyond scientific understanding.'),
    ('Urban', 'GENRE: Urban: Set in a city environment, focusing on urban lifestyle, challenges, and culture.'),
    ('Steampunk', 'GENRE: Steampunk: Features retro-futuristic inventions and steam-powered machinery set in the Victorian era or an analogous alternative historical setting.'),
    ('Dystopian', 'GENRE: Dystopian: Explores a society characterized by oppression, misery, and the dystopian aspects of a controlled state.'),
    ('Espionage', 'GENRE: Espionage: Centers around spies, secret agents, and covert operations, focusing on intrigue, betrayal, and high-stakes plots.'),
    ('Legal Drama', 'GENRE: Legal Drama: Revolves around legal and judicial settings, focusing on crime, justice, and moral dilemmas.'),
    ('War', 'GENRE: War: Deals with armed conflicts, focusing on battles, military strategy, and the human experience within war.'),
    ('Crime', 'GENRE: Crime: Focuses on criminal activities, the pursuit of justice, and the moral complexities of law enforcement and criminals.'),
    ('Biographical', 'GENRE: Biographical: Based on the life of a real person, exploring their experiences, challenges, and the impact they have made on the world.'),
    ('Political Drama', 'GENRE: Political Drama: Centers around political power struggles, governmental affairs, and the personal and ethical issues faced by those in power.'),
    ('Psychological Thriller', 'GENRE: Psychological Thriller: Explores the psychological states of characters, including mental challenges, obsessions, and complex relationships.'),
    ('Medical Drama', 'GENRE: Medical Drama: Revolves around medical professionals and hospitals, focusing on their personal and professional challenges.'),
    ('Spy Fiction', 'GENRE: Spy Fiction: Deals with espionage and intelligence, often featuring complex plots, exotic locations, and high-stakes intrigue.'),
    ('Slice of Life', 'GENRE: Slice of Life: Focuses on everyday experiences and the mundane aspects of characters lives, emphasizing realism and naturalism.'),
    ('Tragedy', 'GENRE: Tragedy: Centers on serious and somber themes, often leading to a sad or disastrous conclusion that evokes pity and fear.'),
    ('Comedy', 'GENRE: Comedy: Incorporates humor and satire, focusing on making the audience laugh through misunderstandings, bizarre situations, or witty dialogue.'),
    ('Musical', 'GENRE: Musical: Combines narrative with musical numbers; the story is often driven by and integrated with the music and dance performances.'),
    ('Eco-fiction', 'GENRE: Eco-fiction: Explores environmental themes, often focusing on the impact of human activity on nature and the planet.'),
    ('Folklore', 'GENRE: Folklore: Draws on traditional beliefs, myths, and stories from various cultures, often bringing ancient tales into modern settings or interpretations.'),
    ('Paranormal', 'GENRE: Paranormal: Involves experiences that are outside the norm, including ghosts, extrasensory perception, and other supernatural phenomena.'),
    ('Time Travel', 'GENRE: Time Travel: Focuses on characters traveling through time, exploring the consequences of changing history or experiencing different eras.'),
    ('Utopian', 'GENRE: Utopian: Explores idealized worlds and societies, often contrasting these with the imperfections of reality.'),
    ('Mythological', 'GENRE: Mythological: Based on ancient myths, gods, and heroes, often reinterpreted or expanded upon to fit into new stories.'),
    ('Superhero', 'GENRE: Superhero: Centers on characters with extraordinary powers or abilities, focusing on their struggles, the ethical dilemmas they face, and their battles against evil.'),
    ('Zombie Apocalypse', 'GENRE: Zombie Apocalypse: Deals with survival in a world overrun by zombies, focusing on the human response to the crisis.'),
    ('Detective', 'GENRE: Detective: Revolves around a detective solving mysteries, often involving murder, crime, and complex puzzles.'),
    ('Apocalyptic', 'GENRE: Apocalyptic: Focuses on end-of-the-world scenarios, exploring how characters deal with impending doom or massive global crises.'),
]


SETTING_CHOICES = [
    ('Cyberpunk City', 'SETTING: Cyberpunk City: A high-tech, low-life futuristic city characterized by advanced technology, cybernetics, and social disparity.'),
    ('Medieval Kingdom', 'SETTING: Medieval Kingdom: Castles, knights, and feudal systems, often involving political intrigue or epic battles.'),
    ('Space Station', 'SETTING: Space Station: A human or alien outpost in outer space, possibly involving isolation, exploration, or cosmic threats.'),
    ('Underwater World', 'SETTING: Underwater World: An exploration of life under the sea, featuring advanced technology or mysterious civilizations.'),
    ('Post-Apocalyptic Wasteland', 'SETTING: Post-Apocalyptic Wasteland: A world after a catastrophic disaster, focusing on survival among ruins and remnants of the past society.'),
    ('Fantasy Realm', 'SETTING: Fantasy Realm: A world of magic, mythical creatures, and legendary quests, often rich with lore and conflict.'),
    ('Modern City', 'SETTING: Modern City: Contemporary urban setting, dealing with crime, life, or the complexities of modern society.'),
    ('Ancient Civilization', 'SETTING: Ancient Civilization: Exploring historical or mythological civilizations like Ancient Egypt, Rome, or Aztec cultures.'),
    ('Dystopian Society', 'SETTING: Dystopian Society: A repressive and controlled setting with Orwellian overtones, focusing on themes of resistance and freedom.'),
    ('Wild West Town', 'SETTING: Wild West Town: Lawmen, outlaws, and duels in a dusty, sprawling frontier of the American West.'),
    ('Haunted House', 'SETTING: Haunted House: Ghosts and supernatural occurrences in an old, mysterious house with a dark history.'),
    ('Steampunk City', 'SETTING: Steampunk City: Victorian-era technology powered by steam, featuring gears, airships, and anachronistic innovations.'),
    ('Virtual Reality', 'SETTING: Virtual Reality: A digital world that can mimic real life or present wholly fantastical environments, often used to blur lines between reality and simulation.'),
    ('Island Paradise', 'SETTING: Island Paradise: Seemingly idyllic but with potential hidden threats or mysteries, perfect for adventure or survival stories.'),
    ('Frozen Tundra', 'SETTING: Frozen Tundra: A harsh, cold environment that challenges survival, possibly with hidden secrets beneath the ice.'),
    ('Alien Planet', 'SETTING: Alien Planet: Otherworldly landscapes, strange creatures, and exotic challenges to survival and exploration.'),
    ('War-Torn Country', 'SETTING: War-Torn Country: A setting ravaged by war, focusing on the human element, survival, and the morality of conflict.'),
    ('Gothic Town', 'SETTING: Gothic Town: Dark, brooding environments with an aesthetic of decay, perfect for horror and mystery narratives.'),
    ('Jungle Environment', 'SETTING: Jungle Environment: Lush, dense jungles that hide ancient ruins, tribes, and untold dangers.'),
    ('Suburban Town', 'SETTING: Suburban Town: Everyday settings that might hide sinister secrets or serve as the ground for extraordinary events.'),
    ('Interdimensional Spaces', 'SETTING: Interdimensional Spaces: Locations that defy standard physics, often involving puzzles and exploration of novel mechanics.'),
    ('Desert Oasis', 'SETTING: Desert Oasis: A sparse, water-centric location in a vast desert, ripe for stories of survival or mythical discoveries.'),
    ('Underground World', 'SETTING: Underground World: Subterranean settings with caves, mines, or even underground civilizations.'),
    ('Heavenly or Mythical Realms', 'SETTING: Heavenly or Mythical Realms: Settings that involve realms of gods, the afterlife, or other spiritual landscapes.'),
    ('Arctic Exploration Base', 'SETTING: Arctic Exploration Base: Isolated from civilization, dealing with the elements and possibly other mysteries locked in ice.'),
    ('Boarding School', 'SETTING: Boarding School: A microcosm of society with its own rules and mini-society, often used for coming-of-age stories.'),
    ('Abandoned City', 'SETTING: Abandoned City: A city that has been mysteriously emptied of its inhabitants, exploring themes of solitude and discovery.'),
    ('Time-Travel Hub', 'SETTING: Time-Travel Hub: A location that facilitates moving between different eras, serving as a narrative device for historical or futuristic exploration.'),
    ('Corporate Megatower', 'SETTING: Corporate Megatower: A setting within a massive building that houses an entire society, often under the control of a powerful corporation.'),
    ('Parallel Universes', 'SETTING: Parallel Universes: Diverse realities that allow for exploration of "what if" scenarios, each with distinct rules and aesthetics.'),
    ('Amusement Park', 'SETTING: Amusement Park: A setting filled with rides and attractions, which can range from joyous and colorful to eerie and abandoned.'),
    ('Ancient Forest', 'SETTING: Ancient Forest: An old, mystical forest filled with ancient trees, mythical creatures, and hidden secrets.'),
    ('Battle Arena', 'SETTING: Battle Arena: A location designed specifically for gladiatorial or other forms of combat, possibly surrounded by spectators.'),
    ('Colonial Settlement', 'SETTING: Colonial Settlement: Early settlements in a new world, dealing with colonization, native interactions, and survival.'),
    ('Deep Space', 'SETTING: Deep Space: The vastness of space beyond known galaxies, exploring isolation, unknown entities, and cosmic phenomena.'),
    ('Dimensional Rift', 'SETTING: Dimensional Rift: An area where the fabric of reality is thin, leading to strange phenomena and crossover events from different dimensions.'),
    ('Dream World', 'SETTING: Dream World: A surreal, often illogical setting where normal rules don\'t apply, derived from the subconscious mind.'),
    ('Fairy Tale Land', 'SETTING: Fairy Tale Land: A whimsical world inspired by fairy tales, filled with magic, archetypal characters, and moral lessons.'),
    ('Giant Spacecraft', 'SETTING: Giant Spacecraft: A massive ship traveling through space, acting as a self-contained world with its own ecosystems and societies.'),
    ('Historical Battlefield', 'SETTING: Historical Battlefield: Real-world historical battle sites, where players can re-enact or alter historical events.'),
    ('Magical Academy', 'SETTING: Magical Academy: A school for wizards or magical beings, focusing on magical education and supernatural challenges.'),
    ('Mega-Corporation Headquarters', 'SETTING: Mega-Corporation Headquarters: The center of a powerful company\'s operations, often a hub of intrigue, technological advancements, and corporate politics.'),
    ('Mental Asylum', 'SETTING: Mental Asylum: A setting that explores psychological themes, often involving escape or the blurring of reality and madness.'),
    ('Mountain Village', 'SETTING: Mountain Village: A remote, often isolated community in the mountains, suitable for survival or adventure stories.'),
    ('Mystical Island', 'SETTING: Mystical Island: An island full of magical properties and ancient mysteries, isolated from the regular world.'),
    ('Pirate Ship', 'SETTING: Pirate Ship: The high seas and pirate vessels, focusing on adventure, treasure hunting, and swashbuckling.'),
    ('Prison', 'SETTING: Prison: A facility for incarceration, where escape, survival, and social dynamics play key roles.'),
    ('Retro-Futuristic City', 'SETTING: Retro-Futuristic City: A city that combines past design aesthetics with futuristic technologies, often used in steampunk or dieselpunk stories.'),
    ('Ruined Civilization', 'SETTING: Ruined Civilization: The remnants of a once-great civilization, now in ruins, offering archaeological and exploratory narratives.'),
    ('Secret Society Headquarters', 'SETTING: Secret Society Headquarters: The hidden base of operations for a clandestine organization, filled with secrets and covert activities.'),
    ('Sky Cities', 'SETTING: Sky Cities: Cities built above the clouds, often inaccessible from the ground, providing a unique and isolated environment.'),
    ('Slum District', 'SETTING: Slum District: A densely populated, underdeveloped area of a city, dealing with themes of poverty, crime, and fighting for survival.'),
    ('Space Colony', 'SETTING: Space Colony: A human settlement on another planet, dealing with themes of colonization, alien interaction, and building a new society.'),
    ('Supernatural Town', 'SETTING: Supernatural Town: A town where supernatural occurrences are the norm, blending everyday life with the paranormal.'),
    ('The Underworld', 'SETTING: The Underworld: A dark, often sinister realm beneath the earth or representing an afterlife, filled with challenges and mythical beings.'),
    ('Time Capsule Town', 'SETTING: Time Capsule Town: A town or city that has remained unchanged for decades or centuries, encapsulating a specific era.'),
    ('Volcanic Island', 'SETTING: Volcanic Island: An island with active volcanoes, exploring themes of natural disaster, survival, and ancient rituals.'),
    ('War-Torn Village', 'SETTING: War-Torn Village: A small community suffering the immediate effects of ongoing conflict, focusing on civilian life during war.'),
    ('Zoological Spaceship', 'SETTING: Zoological Spaceship: A ship designed to transport and study alien wildlife, combining elements of exploration and animal behavior studies.'),
]


TIME_PERIOD_CHOICES = [
    ('Prehistoric', 'TIME PERIOD: Prehistoric: Focuses on the dawn of humanity, involving survival, tribal societies, and interactions with megafauna.'),
    ('Ancient', 'TIME PERIOD: Ancient: Set in ancient civilizations like Egypt, Greece, Rome, or the Americas, often involving mythology, empire-building, and historical events.'),
    ('Classical', 'TIME PERIOD: Classical: Covers the classical period of human history, with a focus on the development of early societies and philosophical advancements.'),
    ('Medieval', 'TIME PERIOD: Medieval: Featuring knights, castles, feudal systems, and often intertwined with elements of fantasy and folklore.'),
    ('Renaissance', 'TIME PERIOD: Renaissance: Emphasizes rebirth in art, science, and culture, suitable for stories of innovation, exploration, and intrigue.'),
    ('Age of Exploration', 'TIME PERIOD: Age of Exploration: Set during the time when explorers traveled the world’s seas, discovering new lands and trading routes.'),
    ('Baroque', 'TIME PERIOD: Baroque: Focused on the ornate aesthetics of the Baroque period, often tied to political intrigue and sprawling empires.'),
    ('Enlightenment', 'TIME PERIOD: Enlightenment: Revolves around the age of reason, science, and philosophical growth, perfect for narratives based on intellectual exploration.'),
    ('Victorian', 'TIME PERIOD: Victorian: Set in the late 19th century, featuring industrial advances, stark social contrasts, and colonial expansions.'),
    ('Edwardian', 'TIME PERIOD: Edwardian: Early 20th century, often considered a period of relative peace before World War I, suitable for tales of societal change.'),
    ('World War I', 'TIME PERIOD: World War I: The setting for military and historical dramas focused on the global impact of the first modern, global war.'),
    ('Roaring Twenties', 'TIME PERIOD: Roaring Twenties: Offers a backdrop of post-war economic boom, prohibition, jazz, and the rise of organized crime.'),
    ('Great Depression', 'TIME PERIOD: Great Depression: Focused on the worldwide economic downturn and its profound effects on society and individual lives.'),
    ('World War II', 'TIME PERIOD: World War II: Another major global conflict setting, ripe for stories of heroism, espionage, and the human spirit.'),
    ('Post-War Era', 'TIME PERIOD: Post-War Era: The reconstruction years after World War II, featuring a mix of optimism and the looming cold war tensions.'),
    ('Cold War', 'TIME PERIOD: Cold War: Ideal for spy thrillers, showcasing espionage, political intrigue, and the nuclear arms race between superpowers.'),
    ('Space Age', 'TIME PERIOD: Space Age: The era of space exploration begins, suitable for both historical narratives and speculative sci-fi adventures.'),
    ('Swinging Sixties', 'TIME PERIOD: Swinging Sixties: A cultural revolution in music, fashion, and liberal lifestyles, perfect for more personal and cultural stories.'),
    ('Disco Era', 'TIME PERIOD: Disco Era: The 1970s, known for its distinct music, fashion, and economic challenges, setting the stage for vibrant social exploration.'),
    ('Late Cold War', 'TIME PERIOD: Late Cold War: The 1980s, marked by political tensions, the rise of technology, and significant cultural shifts.'),
    ('Modern Day', 'TIME PERIOD: Modern Day: Contemporary settings that reflect current technologies, societal issues, and global interactions.'),
    ('Near Future', 'TIME PERIOD: Near Future: A speculative look at the coming decades, often involving technological advancements and potential societal changes.'),
    ('Far Future', 'TIME PERIOD: Far Future: Set in a distant future where human civilization has evolved or drastically changed, often involving space travel and high-tech societies.'),
    ('Post-Apocalyptic', 'TIME PERIOD: Post-Apocalyptic: After an undefined catastrophic event, focusing on survival, reconstruction, and new societal norms.'),
    ('Alternate History', 'TIME PERIOD: Alternate History: A reimagining of historical events where certain outcomes happened differently, leading to a changed world.'),
    ('Mythical Time', 'TIME PERIOD: Mythical Time: Timeless or undefined periods, often used in settings involving gods, mythical creatures, and legendary quests.'),
    ('Eternal or Timeless Realm', 'TIME PERIOD: Eternal or Timeless Realm: Settings that do not adhere to any historical timeline, often used in fantasy or abstract conceptual games.'),
    ('Stone Age', 'TIME PERIOD: Stone Age: Focused on the earliest days of human tool-making and the survival of primitive societies.'),
    ('Bronze Age', 'TIME PERIOD: Bronze Age: A period marked by the development of metal tools and the rise of early urban civilizations.'),
    ('Iron Age', 'TIME PERIOD: Iron Age: Characterized by the spread of ironworking, the formation of new cultural identities, and early empires.'),
    ('Dark Ages', 'TIME PERIOD: Dark Ages: Often associated with the early medieval period in Europe, marked by societal collapse and cultural decline.'),
    ('Mongolian Empire', 'TIME PERIOD: Mongolian Empire: The era of Genghis Khan and the vast Mongol conquests across Asia and Europe.'),
    ('Elizabethan Era', 'TIME PERIOD: Elizabethan Era: The period of Queen Elizabeth I\'s reign, known for the flowering of English drama and the advent of Shakespeare.'),
    ('Tudor Period', 'TIME PERIOD: Tudor Period: Focused on the Tudor dynasty in England, a time of significant religious and political upheaval.'),
    ('Industrial Revolution', 'TIME PERIOD: Industrial Revolution: A pivotal era of industrial growth and technological innovation, changing societies profoundly.'),
    ('American Civil War', 'TIME PERIOD: American Civil War: Set during the 1860s in America, dealing with the conflict between the North and the South.'),
    ('Belle Époque', 'TIME PERIOD: Belle Époque: "Beautiful Era" in Europe before World War I, marked by cultural refinement and economic prosperity.'),
    ('Jazz Age', 'TIME PERIOD: Jazz Age: Often synonymous with the Roaring Twenties but specifically focused on the jazz music scene’s impact on culture.'),
    ('Prohibition Era', 'TIME PERIOD: Prohibition Era: The 1920s in America when alcohol was illegal, leading to bootlegging and organized crime.'),
    ('Atomic Age', 'TIME PERIOD: Atomic Age: Post-World War II, characterized by both the fear and fascination with nuclear power and technology.'),
    ('Hippie Movement', 'TIME PERIOD: Hippie Movement: The 1960s and early 1970s, focused on peace, love, and cultural revolution against conventional norms.'),
    ('Digital Age', 'TIME PERIOD: Digital Age: Late 20th century to present, highlighting the rise of digital technology, the internet, and global connectivity.'),
    ('Information Age', 'TIME PERIOD: Information Age: Overlaps with the Digital Age, focusing on the impact of instant access to information on global societies.'),
    ('Biotech Future', 'TIME PERIOD: Biotech Future: Speculative near-future where biotechnology has transformed health, environment, and industries.'),
    ('Cybernetic Revolution', 'TIME PERIOD: Cybernetic Revolution: A future era where cybernetic enhancements and AI integration are common.'),
    ('Interstellar Age', 'TIME PERIOD: Interstellar Age: A future time when humanity has colonized other star systems, often involving space exploration and alien contact.'),
    ('Age of Discovery', 'TIME PERIOD: Age of Discovery: Not just Earths historical period of global exploration but can be applied to discovering new galaxies or dimensions.'),
    ('Victorian Gothic', 'TIME PERIOD: Victorian Gothic: Combining Victorian elements with gothic horror, focusing on dark, romantic, and mysterious themes.'),
    ('Pre-Columbian Americas', 'TIME PERIOD: Pre-Columbian Americas: Before the arrival of Europeans, focusing on indigenous cultures and civilizations like the Aztecs and Incas.'),
    ('Colonial America', 'TIME PERIOD: Colonial America: Early days of American colonies, focusing on settlement, survival, and interaction with Native Americans.'),
    ('Meiji Restoration', 'TIME PERIOD: Meiji Restoration: The period in Japan when rapid modernization and westernization took place, transitioning from feudalism to modern state.'),
    ('Regency Era', 'TIME PERIOD: Regency Era: Early 19th century in Britain, marked by distinctive trends in architecture, literature, fashions, and politics.'),
    ('French Revolution', 'TIME PERIOD: French Revolution: A tumultuous period marked by radical social and political upheaval in France, offering a rich narrative for power struggles and societal change.'),
    ('Steam Age', 'TIME PERIOD: Steam Age: A speculative period where steam power remains the dominant technology, often used in steampunk settings.'),
    ('Age of Mythology', 'TIME PERIOD: Age of Mythology: Set in a time when myths are real and gods interact directly with humans, offering a rich tapestry for epic narratives.')
]


STORY_TYPE_CHOICES = [
    ('Hero\'s Journey', 'STORY TYPE: Hero\'s Journey: A classic narrative where the protagonist goes on an adventure, faces trials, receives aid, and eventually returns home transformed.'),
    ('Revenge', 'STORY TYPE: Revenge: Centers around a protagonist seeking vengeance against an antagonist or system that has wronged them or their loved ones.'),
    ('Redemption', 'STORY TYPE: Redemption: Focuses on a flawed character who seeks to make amends for past mistakes and find redemption through personal growth or heroic acts.'),
    ('Coming of Age', 'STORY TYPE: Coming of Age: Explores the growth of a protagonist from youth to adulthood, learning valuable life lessons along the way.'),
    ('Tragedy', 'STORY TYPE: Tragedy: Involves a protagonist with a fatal flaw leading to their downfall, emphasizing the darker aspects of human nature and fate.'),
    ('Mystery', 'STORY TYPE: Mystery: Revolves around a puzzling or unsolved event, requiring the protagonist to uncover secrets and solve the mystery.'),
    ('Romance', 'STORY TYPE: Romance: Focuses on the relationship and emotional bond between characters, often dealing with obstacles to their love.'),
    ('Survival', 'STORY TYPE: Survival: Characters are placed in a hostile environment where the primary goal is surviving against odds, be they natural, human, or supernatural.'),
    ('Conspiracy', 'STORY TYPE: Conspiracy: Involves a plot where the protagonist uncovers a conspiracy among powerful groups, with high stakes and dramatic revelations.'),
    ('Rags to Riches', 'STORY TYPE: Rags to Riches: Follows a protagonist\'s ascent from poor beginnings to success, often overcoming significant obstacles along the way.'),
    ('Quest', 'STORY TYPE: Quest: Involves a main task or goal that the protagonist must complete, usually involving a journey and several sub-tasks.'),
    ('Escape', 'STORY TYPE: Escape: The protagonist must escape from a confining or dangerous situation, requiring ingenuity and perseverance.'),
    ('Rescue', 'STORY TYPE: Rescue: Centers around the protagonist\'s efforts to rescue others from danger, showcasing themes of bravery and self-sacrifice.'),
    ('Adventure', 'STORY TYPE: Adventure: Characterized by an exciting and risky journey undertaken by the protagonist or a group of characters.'),
    ('Discovery', 'STORY TYPE: Discovery: Focuses on the uncovering of something significant or unknown, be it physical discoveries or internal realizations.'),
    ('Transformation', 'STORY TYPE: Transformation: A story that involves significant changes in the setting, characters, or society, often driven by internal or external forces.'),
    ('Sacrifice', 'STORY TYPE: Sacrifice: The protagonist makes a significant sacrifice for the greater good, emphasizing themes of altruism and moral decisions.'),
    ('Oppression', 'STORY TYPE: Oppression: Revolves around a protagonist or group struggling against an oppressive force or regime, seeking freedom or justice.'),
    ('Betrayal', 'STORY TYPE: Betrayal: Focuses on the protagonist dealing with the fallout and consequences of being betrayed by someone close or trusted.'),
    ('Utopia/Dystopia', 'STORY TYPE: Utopia/Dystopia: Explores idealized or nightmarish societies, often examining the implications of political or technological changes.'),
    ('Psychological', 'STORY TYPE: Psychological: Delves into the mental states of characters, exploring psychological conflicts and complex emotional experiences.'),
    ('War', 'STORY TYPE: War: Narratives centered around conflicts, strategies, and the experiences of those involved in wars, both historical and fictional.'),
    ('Epic', 'STORY TYPE: Epic: Large-scale stories with multiple characters and intertwining plots, often set against a grand historical or mythological backdrop.'),
    ('Satire', 'STORY TYPE: Satire: Uses humor, irony, exaggeration, or ridicule to criticize or expose the flaws of a society, individual, or system.'),
    ('Paranormal', 'STORY TYPE: Paranormal: Involves elements that are beyond the scope of scientific understanding, dealing with supernatural forces or creatures.'),
    ('Time Travel', 'STORY TYPE: Time Travel: Focuses on characters traveling through time and experiencing different eras, often dealing with the consequences of changing events.'),
    ('Heist', 'STORY TYPE: Heist: Centers on planning and executing a theft or a series of thefts, focusing on the tactics and the interpersonal dynamics of the crew.'),
    ('Political Intrigue', 'STORY TYPE: Political Intrigue: Deals with the manipulation and power struggles within a political setting, often involving corruption and tactical alliances.'),
    ('Allegory', 'STORY TYPE: Allegory: Uses symbolic figures, actions, or representations to express broader truths about human existence or society.'),
    ('Biographical', 'STORY TYPE: Biographical: Tells the story of a person\'s life, emphasizing key events and achievements that define their impact on the world.'),
    ('Ensemble Drama', 'STORY TYPE: Ensemble Drama: Focuses on the interwoven lives and personal stories of a group of characters, each with their unique perspective.'),
    ('Espionage', 'STORY TYPE: Espionage: Involves spies and secret agents, focusing on stealth, information gathering, and the tensions of undercover operations.'),
    ('Ecological', 'STORY TYPE: Ecological: Centers around environmental issues, the relationship between humans and nature, and often includes a message about conservation.'),
    ('Exploration', 'STORY TYPE: Exploration: Characters venture into unknown territories or realms, discovering new worlds and uncovering hidden truths.'),
    ('Fable', 'STORY TYPE: Fable: A narrative that conveys a moral lesson, often involving animals as characters with human traits.'),
    ('Folk Tale', 'STORY TYPE: Folk Tale: Based on traditional stories passed down through generations, often imbued with cultural significance and moral lessons.'),
    ('Frame Story', 'STORY TYPE: Frame Story: A main narrative that serves as a structure for one or more stories within it. Each subplot can be connected or thematic.'),
    ('Ghost Story', 'STORY TYPE: Ghost Story: Focuses on the supernatural and interactions with the spirit world, often aiming to evoke a sense of horror or mystery.'),
    ('Gothic', 'STORY TYPE: Gothic: Combines fiction, horror, death, and romance, often set against a backdrop of decayed settings to create a sense of fear and wonder.'),
    ('Historical Fiction', 'STORY TYPE: Historical Fiction: While based on historical facts, these stories are embellished with fictional characters and plots, enriching the understanding of the past.'),
    ('Intrigue', 'STORY TYPE: Intrigue: Centers around complex plots of manipulation, deceit, and secretive schemes, often within a political or royal court setting.'),
    ('Legal Drama', 'STORY TYPE: Legal Drama: Focuses on the legal system, where protagonists are typically lawyers, judges, or plaintiffs dealing with moral and ethical dilemmas.'),
    ('Metafiction', 'STORY TYPE: Metafiction: A narrative that self-consciously addresses the devices of fiction, possibly breaking the fourth wall or discussing its own creation.'),
    ('Morality Tale', 'STORY TYPE: Morality Tale: A story that explores moral conflicts, decisions, and their consequences, often teaching a specific moral lesson.'),
    ('Mythic', 'STORY TYPE: Mythic: Incorporates traditional myths into modern settings or reinterprets these ancient stories in new, imaginative ways.'),
    ('Philosophical', 'STORY TYPE: Philosophical: Explores philosophical questions within the context of the narrative, engaging with ideas about existence, morality, and human nature.'),
    ('Picaresque', 'STORY TYPE: Picaresque: Centers on a roguish but "appealing" hero of low social class who lives by their wits in a corrupt society.'),
    ('Postmodern', 'STORY TYPE: Postmodern: Characterized by reliance on narrative techniques such as fragmentation, paradox, unreliable narrators, and an emphasis on the subjective interpretation of reality.'),
    ('Procedural', 'STORY TYPE: Procedural: Focuses on a series of methodical, technical actions, typically involving law enforcement, medical, or other procedural tasks.'),
    ('Rebirth', 'STORY TYPE: Rebirth: Involves the fall and rise of a main character, who often experiences a profound transformation or enlightenment.'),
    ('Road', 'STORY TYPE: Road: Centers around a journey, offering a straightforward plot that explores the characters and their relationships through travel.'),
    ('Robinsonade', 'STORY TYPE: Robinsonade: Focuses on the survival of a protagonist stranded in a desolate location, emphasizing self-sufficiency, ingenuity, and the human spirit.'),
    ('Slice of Cyber-life', 'STORY TYPE: Slice of Cyber-life: Explores everyday life and social issues within a futuristic or cybernetic setting, emphasizing how ordinary people adapt to technological changes.'),
    ('Speculative', 'STORY TYPE: Speculative: Explores futuristic, imaginative, or technologically advanced content, providing a playground for exploring "what if?" scenarios.'),
    ('Urban Fantasy', 'STORY TYPE: Urban Fantasy: Combines magical elements with modern settings, where fantasy narratives are woven into real-world urban environments.'),
    ('Voyage and Return', 'STORY TYPE: Voyage and Return: A narrative where the protagonist goes to a strange land, faces trials, and returns home with experience and wisdom.'),
]


PACE_CHOICES = [
    ('Breakneck', 'PACE: Breakneck - Rapid and intense, often used in action games where quick decisions and reactions are crucial.'),
    ('Steady', 'PACE: Steady - A consistent pace that keeps the story moving forward without abrupt changes, suitable for most traditional RPGs.'),
    ('Measured', 'PACE: Measured - Deliberate and controlled, often used in games with complex storylines where players need time to absorb and reflect on information.'),
    ('Slow Burn', 'PACE: Slow Burn - Gradually builds tension or story elements, often used in horror or thriller games that aim to immerse and gradually unsettle the player.'),
    ('Epic', 'PACE: Epic - Long and drawn-out, suitable for grand-scale narratives that span vast worlds or long periods, typical of epic RPGs or adventure games.'),
    ('High-Octane', 'PACE: High-Octane - Intensely fast and energetic, commonly seen in high-action shooters or racing games where adrenaline is a key component.'),
    ('Leisurely', 'PACE: Leisurely - Slow and relaxing, perfect for simulation games or games that emphasize exploration and experimentation without urgent goals.'),
    ('Variable', 'PACE: Variable - Features alternating periods of fast and slow pacing, suitable for games that incorporate multiple gameplay styles or shifting narrative tones.'),
    ('Pulsating', 'PACE: Pulsating - Cycles between intense bursts of activity and calmer periods, creating a dynamic rhythm that can keep players engaged and on edge.'),
    ('Intermittent', 'PACE: Intermittent - Consists of bursts of action followed by long periods of downtime or minimal activity, common in survival or strategy games where planning phases are crucial.'),
    ('Moderate', 'PACE: Moderate - A middle-ground pace that allows for steady development of both story and gameplay, often used in action-adventure games.'),
    ('Rhythmic', 'PACE: Rhythmic - Has a flow that feels almost musical, where gameplay and story elements are introduced in a patterned sequence, enhancing the immersive experience.'),
    ('Accelerating', 'PACE: Accelerating - Starts slow and picks up speed as the story progresses, often used in narrative games to build climax and suspense.'),
    ('Decelerating', 'PACE: Decelerating - Begins with intense action or complex narrative and slows towards the end, allowing for a reflective or conclusive experience.'),
    ('Non-linear', 'PACE: Non-linear - Pace varies based on player choices, often seen in open-world games or interactive dramas where player actions significantly influence the story flow.'),
    ('Segmented', 'PACE: Segmented - Clearly divided into sections or chapters that may each have their own pacing, common in episodic games or games with distinct acts.'),
    ('Wave-like', 'PACE: Wave-like - Features ups and downs in action and intensity, mimicking the natural flow of a wave, suited for games that want to emulate real-life cycles.'),
    ('Halted', 'PACE: Halted - Intermittent stops and starts in the narrative or gameplay, often used for dramatic effect or to emphasize puzzle-solving or critical story points.'),
    ('Flash', 'PACE: Flash - Very rapid scenes or changes, almost chaotic, used effectively in games that aim to disorient or challenge the player’s perception of the story.'),
    ('Glacial', 'PACE: Glacial - Extremely slow, allowing for deep world-building and complex character development, suited for immersive simulations or detailed RPGs.'),
    ('Erratic', 'PACE: Erratic - Unpredictable fluctuations in speed, making the gameplay feel spontaneous or chaotic, useful in games involving madness or surreal experiences.'),
    ('Cinematic', 'PACE: Cinematic - Mimics the pacing of films, with well-timed climaxes and resolutions, often used in story-driven games that focus heavily on narrative impact.'),
    ('Methodical', 'PACE: Methodical - Slow and systematic, emphasizing strategic planning and thoughtful decision-making, common in turn-based strategy or puzzle games.'),
    ('Expansive', 'PACE: Expansive - Gradual unfolding of game elements and story over a long period, suitable for massive open-world games where exploration is a key feature.'),
    ('Intensive', 'PACE: Intensive - Consistently demanding, keeping players continuously engaged with tasks or challenges, typical in survival games or intensive RPGs.'),
    ('Layered', 'PACE: Layered - Complex pacing with multiple threads running at different speeds, common in games with several subplots or multiple playable characters.'),
    ('Sporadic', 'PACE: Sporadic - Infrequent bursts of action or plot progression, creating an environment of uncertainty and anticipation, suitable for horror or thriller games.'),
    ('Relaxed', 'PACE: Relaxed - Gentle and easygoing, allowing players to explore at their own pace without pressure, ideal for casual or lifestyle games.'),
    ('Compounding', 'PACE: Compounding - Each segment builds on the intensity of the previous, leading to a climax, used in games that aim to gradually increase the stakes.'),
    ('Repetitive', 'PACE: Repetitive - Cycles of similar events or actions, which can be used deliberately to create themes or highlight monotony within the game\'s world.'),
    ('Asynchronous', 'PACE: Asynchronous - Different parts of the game or story may progress at different rates, which can reflect divergent storylines or player choices affecting different areas of the game world.'),
    ('Ebbing', 'PACE: Ebbing - Like a tide, where the pace naturally flows in and then recedes, providing players with time to explore deeply and then retreat to process or plan.'),
    ('Progressive', 'PACE: Progressive - Steadily increases in speed or intensity as players advance, pushing them to adapt and grow along with the game.'),
    ('Syncopated', 'PACE: Syncopated - Contains unexpected changes in pacing, which can keep players engaged and attentive, often used to surprise or challenge the player.'),
    ('Seasonal', 'PACE: Seasonal - Reflects changes similar to seasons, where different phases of the game might have different pacing, echoing natural or story-driven cycles.'),
    ('Pendulum', 'PACE: Pendulum - Swings back and forth between fast and slow, allowing for intense periods followed by calm, which can help manage game tension and relief.'),
    ('Feast-or-Famine', 'PACE: Feast-or-Famine - Alternates between periods of abundance (where action is constant and rewards are plentiful) and scarcity (where challenges are greater and resources are limited).'),
    ('Crescendo', 'PACE: Crescendo - A slow build-up leading to a peak of activity or climax, effectively used in musical or performance-based games.'),
    ('Time-lapse', 'PACE: Time-lapse - Speeds up certain segments to show progress or change over time, which can be useful in simulation or growth-focused games.'),
    ('Punctuated', 'PACE: Punctuated - Defined by significant events that change the pace abruptly, leading to a dynamic narrative structure that reflects pivotal changes or twists in the storyline.'),
]

STORY_TONE_CHOICES = [
    ('Dramatic', 'TONE: Dramatic - Serious in nature and presentation, often involving intense character conflicts and high stakes.'),
    ('Light-hearted', 'TONE: Light-hearted - Playful and often humorous, making for an enjoyable and easy-going gameplay experience.'),
    ('Mysterious', 'TONE: Mysterious - Creates a sense of intrigue and curiosity, with hidden secrets and puzzles driving the narrative.'),
    ('Dark', 'TONE: Dark - Features grim or bleak themes, often used in horror or noir genres to evoke feelings of fear or discomfort.'),
    ('Suspenseful', 'TONE: Suspenseful - Keeps players on edge through uncertainty and tension, commonly used in thriller and mystery genres.'),
    ('Romantic', 'TONE: Romantic - Focuses on affection, relationships, and emotional connections between characters.'),
    ('Tragic', 'TONE: Tragic - Characterized by sorrowful or disastrous events, evoking pity or sadness to deepen emotional engagement.'),
    ('Comedic', 'TONE: Comedic - Relies on humor to lighten the mood, entertain, and sometimes provide satire or social commentary.'),
    ('Inspiring', 'TONE: Inspiring - Aimed at uplifting and motivating the player through positive messages and heroic deeds.'),
    ('Sombre', 'TONE: Sombre - Reflects a gloomy or subdued mood, suitable for narratives involving loss, reflection, or serious themes.'),
    ('Eerie', 'TONE: Eerie - Conjures an atmosphere of unease or strangeness, perfect for supernatural or unsettling scenarios.'),
    ('Epic', 'TONE: Epic - Conveys grandeur and awe, often in stories that involve vast settings, high stakes, and heroic quests.'),
    ('Whimsical', 'TONE: Whimsical - Capriciously quaint, fanciful, or playful, particularly in fantasy or magical settings.'),
    ('Melancholic', 'TONE: Melancholic - Reflects a thoughtful sadness or contemplativeness, often used in stories of loss or existential reflection.'),
    ('Bittersweet', 'TONE: Bittersweet - Combining elements of both sweet and bitter, these stories have happy moments tinged with sadness, or vice versa.'),
    ('Nostalgic', 'TONE: Nostalgic - Evokes a longing for the past, often used in games that reference or are set in a bygone era.'),
    ('Hopeful', 'TONE: Hopeful - Despite challenges or setbacks, the tone remains optimistic, suggesting positive outcomes are possible.'),
    ('Gritty', 'TONE: Gritty - Raw and tough, often showcasing the harsh realities of life within the game’s world.'),
    ('Cynical', 'TONE: Cynical - Features a skeptical or contemptuous view of human nature, often used in noir or dystopian settings.'),
    ('Tense', 'TONE: Tense - High-strung and nerve-wracking, suitable for action-packed or high-stakes game scenarios.'),
    ('Foreboding', 'TONE: Foreboding - Implies that something bad or dangerous is on the horizon, building anticipation and caution.'),
    ('Satirical', 'TONE: Satirical - Critiques and mocks, often subtly, societal norms or behaviors through exaggeration or irony.'),
    ('Surreal', 'TONE: Surreal - Elements that are fantastical or bizarre, bending the rules of reality to create dream-like scenarios.'),
    ('Chilling', 'TONE: Chilling - Intensely cold or terrifying, particularly effective in horror games to evoke fear.'),
    ('Reflective', 'TONE: Reflective - Encourages thought about deeper meanings or implications of the story or characters’ actions.'),
    ('Enigmatic', 'TONE: Enigmatic - Full of mystery or ambiguity, making the story puzzling and compelling to unfold.'),
    ('Adventurous', 'TONE: Adventurous - Conveys a sense of excitement and exploration, often used in action-adventure or quest-driven games.'),
    ('Gothic', 'TONE: Gothic - Dark and brooding with an emphasis on horror, death, and the romanticism of despair.'),
    ('Sentimental', 'TONE: Sentimental - Emphasizes emotional or tender feelings, aiming to connect deeply with the player’s personal memories or feelings.'),
    ('Rousing', 'TONE: Rousing - Designed to stir up enthusiastic support or interest, often through inspiring speeches, heroic acts, or thrilling victories.'),
    ('Poignant', 'TONE: Poignant - Evokes a keen sense of sadness or regret, often through deeply emotional or reflective storytelling.'),
    ('Uplifting', 'TONE: Uplifting - Provides a mood of cheerfulness and optimism, encouraging players through positive outcomes and inspiring stories.'),
    ('Menacing', 'TONE: Menacing - Creates a threatening or dangerous atmosphere, ideal for games that involve tension and potential peril.'),
    ('Mystical', 'TONE: Mystical - Enchants and mesmerizes, incorporating elements of the magical or unknown to captivate the player’s imagination.'),
    ('Aggressive', 'TONE: Aggressive - Marked by or resulting from aggression, often used in combat-heavy games or those involving intense rivalries.'),
    ('Calm', 'TONE: Calm - Peaceful and tranquil, suitable for games focused on relaxation, meditation, or gentle exploration.'),
    ('Ironic', 'TONE: Ironic - Involves a contrast between expectations and reality, often humorous or bitterly mocking in nature.'),
    ('Stoic', 'TONE: Stoic - Characterized by a lack of visible emotion, emphasizing inner strength or endurance in the face of hardship.'),
    ('Dreamy', 'TONE: Dreamy - Soft, light, and slightly disconnected from reality, suitable for surreal narratives or romance.'),
    ('Anguished', 'TONE: Anguished - Intense suffering or pain, often emotional, portrayed through the narrative or character experiences.'),
    ('Futuristic', 'TONE: Futuristic - Deals with themes of the future, technology, and innovation, often mixed with hope or caution about what is to come.'),
    ('Playful', 'TONE: Playful - Light-hearted and fun, focusing on enjoyment and often interactive elements that engage players in light challenges.'),
    ('Philosophical', 'TONE: Philosophical - Explores fundamental questions about life, purpose, and the human condition, often encouraging players to think deeply.'),
    ('Macabre', 'TONE: Macabre - Focused on the grim or grotesque aspects of death, often intertwined with horror or gothic elements.'),
    ('Conspiratorial', 'TONE: Conspiratorial - Centers on secret plans and plots, imbuing the narrative with a sense of mystery and hidden truths.'),
    ('Thrilling', 'TONE: Thrilling - Provides excitement and suspense, often through action-packed sequences or unpredictable plot twists.'),
    ('Alluring', 'TONE: Alluring - Captivates the players interest through charm or intrigue, often used in mystery or romance genres.'),
    ('Quirky', 'TONE: Quirky - Characterized by odd or unexpected traits, especially in characters or world-building, leading to unique and unconventional narratives.'),
    ('Introspective', 'TONE: Introspective - Focuses on the internal thoughts and emotions of characters, encouraging players to reflect alongside them.'),
    ('Dystopian', 'TONE: Dystopian - Depicts an imagined state or society in which there is great suffering or injustice, typically one that is totalitarian or post-apocalyptic.'),
    ('Baroque', 'TONE: Baroque - Characterized by extravagance, complexity, or flamboyance, which can be reflected in both the visual style and storytelling.'),
    ('Pastoral', 'TONE: Pastoral - Idealizes country life and nature, often contrasting the simplicity and serenity of rural living against the complexities of urban life or adventure.'),
    ('Vibrant', 'TONE: Vibrant - Full of energy and enthusiasm; bright and vivid storytelling that often features dynamic characters and a colorful setting.'),
    ('Sobering', 'TONE: Sobering - Serious and thoughtful, often involving stark realities or lessons that give pause and provoke serious contemplation.'),
    ('Subversive', 'TONE: Subversive - Seeks to undermine or challenge traditional conventions and ideas, offering alternative perspectives or controversial takes.'),
    ('Eccentric', 'TONE: Eccentric - Odd or unusual in a compelling and interesting way, often used to create memorable and distinctive characters or settings.'),
    ('Morbid', 'TONE: Morbid - Characterized by an abnormal and unhealthy interest in disturbing and unpleasant subjects, especially death and disease.'),
    ('Absurdist', 'TONE: Absurdist - Focuses on the experiences of characters who face the apparent meaninglessness of life, often through bizarre or surreal scenarios.'),
]

WRITING_STYLE_CHOICES = [
    ('Descriptive', 'STYLE: Descriptive - Rich in details, painting vivid pictures of settings, characters, and events to immerse the player fully.'),
    ('Expository', 'STYLE: Expository - Focuses on informative and explanatory types of writing, often used to convey background information, game mechanics, or world-building elements.'),
    ('Conversational', 'STYLE: Conversational - Uses a casual and engaging tone, as if characters are speaking directly to the player, making interactions feel more personal and relatable.'),
    ('Minimalist', 'STYLE: Minimalist - Strips down the narrative to its essential parts, avoiding over-explanation to allow players to fill in the gaps with their imagination.'),
    ('Flowery', 'STYLE: Flowery - Employs ornate and elaborate language, often to create a sense of beauty or historical authenticity.'),
    ('Technical', 'STYLE: Technical - Incorporates jargon and complex terminology, suitable for games with deep mechanics or scientific themes.'),
    ('Dramatic', 'STYLE: Dramatic - Emphasizes emotion and conflict, designed to engage players deeply and evoke strong responses.'),
    ('Humorous', 'STYLE: Humorous - Light-hearted and often comedic, incorporating jokes, puns, and amusing situations to entertain and engage players.'),
    ('Epistolary', 'STYLE: Epistolary - Told through documents, letters, diary entries, or other in-game texts, providing a first-person view and historical context.'),
    ('Lyrical', 'STYLE: Lyrical - Uses a poetic tone, often employing rhythm and flow to evoke a certain mood or atmosphere.'),
    ('Objective', 'STYLE: Objective - Presents information in a straightforward and unemotional manner, often used in simulations or strategy games where clarity is crucial.'),
    ('Subjective', 'STYLE: Subjective - Reflects personal impressions and emotions, often used in RPGs and adventure games to deepen character development.'),
    ('Symbolic', 'STYLE: Symbolic - Uses symbols and metaphors to convey deeper meanings, adding layers of interpretation to the narrative.'),
    ('Satirical', 'STYLE: Satirical - Criticizes or mocks traditional conventions through wit and irony, often used to comment on society or player expectations.'),
    ('Allegorical', 'STYLE: Allegorical - Conveys messages or moral lessons through symbolic figures, actions, or imagery, often to discuss larger philosophical or ethical issues.'),
    ('Narrative', 'STYLE: Narrative - Tells a story with a clear beginning, middle, and end, focusing on plot development and character arcs.'),
    ('Dialogic', 'STYLE: Dialogic - Focuses heavily on dialogue between characters to drive the narrative and reveal information.'),
    ('Stream of Consciousness', 'STYLE: Stream of Consciousness - Mimics the continuous flow of a character’s thoughts and feelings, often used to give deep psychological insight.'),
    ('Non-linear', 'STYLE: Non-linear - Features a disjointed narrative structure, allowing players to piece together the story from multiple, non-sequential segments.'),
    ('Analytical', 'STYLE: Analytical - Breaks down complex ideas or themes for the player, often used in games that require strategic thinking or problem-solving.'),
    ('Didactic', 'STYLE: Didactic - Intends to teach or instruct, especially moral or ethical lessons, through the narrative or character experiences.'),
    ('Persuasive', 'STYLE: Persuasive - Aims to convince the player of a particular viewpoint or decision, often used in games involving moral choices or debates.'),
    ('Flashback', 'STYLE: Flashback - Frequently uses past events to add context or depth to the current narrative, allowing for a deeper understanding of characters and story.'),
    ('Mythic', 'STYLE: Mythic - Incorporates elements of myths and legends, often using a grandiose style to elevate the narrative.'),
    ('Folkloric', 'STYLE: Folkloric - Emulates the tone and style of traditional folk tales, often involving moral lessons, mythical creatures, or epic quests.'),
    ('Gothic', 'STYLE: Gothic - Creates a dark and mysterious atmosphere, using detailed descriptions and a tone that enhances the supernatural or horror elements.'),
    ('Hard-boiled', 'STYLE: Hard-boiled - Features a tough, unsentimental tone, often used in detective or crime narratives.'),
    ('Journalistic', 'STYLE: Journalistic - Employs a clear, factual style of writing that reports events as they happen, suitable for war games or historical reenactments.'),
    ('Interactive', 'STYLE: Interactive - Adapts to player choices, changing the narrative delivery based on interaction, emphasizing agency and personal impact on the story.'),
    ('Colloquial', 'STYLE: Colloquial - Uses everyday language and slang, giving the narrative a more relaxed and informal feel, which can help in characterizing specific regions or age groups.'),
    ('Oratorical', 'STYLE: Oratorical - Employs a formal, persuasive, and often pompous style, commonly found in speeches or debates within games.'),
    ('Euphemistic', 'STYLE: Euphemistic - Uses mild or indirect expressions to discuss harsh or unpleasant realities, often to soften the impact or to suit a younger audience.'),
    ('Parodic', 'STYLE: Parodic - Imitates or exaggerates the typical elements of a genre, style, or particular work to create a comic effect or critique.'),
    ('Chivalric', 'STYLE: Chivalric - Mimics the medieval tales of chivalry, combining idealism, adventure, and courtly love, suitable for fantasy or historical settings.'),
    ('Forensic', 'STYLE: Forensic - Emphasizes logical argumentation and evidence, often used in mystery or detective games where solving crimes is central.'),
    ('High Fantasy', 'STYLE: High Fantasy - Incorporates an elevated, often formal language to create a sense of grandeur and timeless narrative, common in epic fantasy games.'),
    ('Epigrammatic', 'STYLE: Epigrammatic - Full of witty insights or pithy expressions, often used in character dialogues to enhance personality traits or deliver memorable lines.'),
    ('Sensational', 'STYLE: Sensational - Focuses on exciting and shocking elements to grab attention, commonly used in action or thriller games.'),
    ('Psychoanalytic', 'STYLE: Psychoanalytic - Explores the psychological motivations of characters, often delving into their subconscious or dreams, suitable for narrative-driven or psychological games.'),
    ('Rustic', 'STYLE: Rustic - Relates to rural life, using language and themes associated with the countryside, often evoking a sense of simplicity or pastoral beauty.'),
    ('Socratic', 'STYLE: Socratic - Uses a dialogic method of questioning to stimulate critical thinking and illuminate ideas, suitable for educational or deeply philosophical games.'),
    ('Vulgar', 'STYLE: Vulgar - Incorporates crude and oftentimes offensive language to create a raw and realistic atmosphere, suited for adult-themed or gritty narratives.'),
    ('Esoteric', 'STYLE: Esoteric - Dense with complex terms and concepts that may be difficult for the uninitiated to understand, often used in science fiction or fantasy games that involve detailed world-building.'),
    ('Apocalyptic', 'STYLE: Apocalyptic - Portrays a tone of doom and finality, often used in narratives surrounding end-of-the-world scenarios or deep existential crises.'),
    ('Confessional', 'STYLE: Confessional - Offers a personal, revealing, and sometimes painfully honest look into the narrators or characters own feelings and experiences.'),
    ('Motivational', 'STYLE: Motivational - Designed to inspire and energize players, often used in sports games or stories of personal triumph.'),
    ('Idyllic', 'STYLE: Idyllic - Presents an ideal world or unrealistically perfect scenario, often used to contrast with a storys darker or more realistic elements.'),
    ('Elegiac', 'STYLE: Elegiac - Mournful or melancholic, commemorating something or someone lost, often imbued with a sense of beauty in the face of tragedy.'),
    ('Pastoral', 'STYLE: Pastoral - Evokes life in the countryside, emphasizing naturalness, peace, and simplicity, contrasting with urban or industrial complexities.'),
    ('Exaggerated', 'STYLE: Exaggerated - Uses over-the-top elements to enhance drama or humor, effective in satirical or highly stylized narratives.'),
    ('Understated', 'STYLE: Understated - Deliberately downplays emotional or dramatic elements, often leaving much to the players interpretation or imagination.'),
    ('Polemical', 'STYLE: Polemical - Argumentative, intended to establish a specific viewpoint or to dispute contrary opinions, used in political or ideological narratives.'),
    ('Laconic', 'STYLE: Laconic - Using very few words to convey much meaning, often giving a sharp, direct impact that can add to a characters mystique or the tension of the narrative.'),
    ('Hyperbolic', 'STYLE: Hyperbolic - Characterized by exaggeration for emphasis or effect, typically in more lighthearted or fantastical settings.'),
    ('Cryptic', 'STYLE: Cryptic - Often puzzling and enigmatic, using obscure or ambiguous language to create mystery or to challenge the players perception.'),
]

CHARACTER_TYPE_CHOICES = [
    ('The Hero', 'CHARACTER TYPE: The Hero - Often the protagonist, whose primary role is to fulfill the quest or mission. They typically exhibit bravery, wisdom, or the capacity to evolve.'),
    ('The Villain', 'CHARACTER TYPE: The Villain - The antagonist whose actions oppose the heros objectives, often embodying evil or simply conflicting ideals.'),
    ('The Mentor', 'CHARACTER TYPE: The Mentor - Provides guidance, training, and tools to the hero. This character is often older and wiser, serving as a teacher or counselor.'),
    ('The Sidekick', 'CHARACTER TYPE: The Sidekick - Loyal companions to the hero, often providing comic relief, additional skills, or moral support. They sometimes represent the hero’s conscience.'),
    ('The Love Interest', 'CHARACTER TYPE: The Love Interest - A character who provides a romantic foil to the main protagonist. Their relationship can significantly influence the narrative’s progression.'),
    ('The Trickster', 'CHARACTER TYPE: The Trickster - Offers comic relief but also important insight through cleverness and mischief. They challenge the status quo and disrupt ordinary events.'),
    ('The Outcast', 'CHARACTER TYPE: The Outcast - A character banished from a community or who chooses to leave. Their journey can explore themes of isolation, redemption, or vengeance.'),
    ('The Warrior', 'CHARACTER TYPE: The Warrior - A character skilled in combat, often with a complex code of honor or loyalty. They thrive on challenge and conflict.'),
    ('The Sage', 'CHARACTER TYPE: The Sage - Wise and knowledgeable, often providing wisdom or mystical guidance. They are seekers of truth and often remain somewhat detached from worldly affairs.'),
    ('The Innocent', 'CHARACTER TYPE: The Innocent - Naive or sheltered characters who are often thrust into circumstances beyond their comprehension or control, their purity or naivety highlighting the harshness of the world.'),
    ('The Orphan', 'CHARACTER TYPE: The Orphan - Typically a sympathetic character seeking to belong. Their journey often involves personal growth and self-discovery.'),
    ('The Ruler', 'CHARACTER TYPE: The Ruler - Holds a significant position of power and authority. Their leadership is often tested throughout the narrative.'),
    ('The Caregiver', 'CHARACTER TYPE: The Caregiver - Selfless and nurturing, often putting the needs of others before their own. They provide emotional support and aid to other characters.'),
    ('The Rebel', 'CHARACTER TYPE: The Rebel - Challenges authority or the status quo, often acting as a catalyst for change. They can be unpredictable and revolutionary.'),
    ('The Explorer', 'CHARACTER TYPE: The Explorer - Always seeking new experiences, driven by curiosity and wanderlust. Their journeys can lead to important discoveries or insights.'),
    ('The Creator', 'CHARACTER TYPE: The Creator - Driven to create something of enduring value or beauty, often artists, scientists, or inventors in narratives.'),
    ('The Jester', 'CHARACTER TYPE: The Jester - Values fun and enjoyment above all else. They often help other characters to see the humorous side of difficult situations.'),
    ('The Magician', 'CHARACTER TYPE: The Magician - Wields significant power, often magical or technological, and can alter reality. Their abilities can be pivotal to the narrative.'),
    ('The Everyman', 'CHARACTER TYPE: The Everyman - Relatable and ordinary, this character type resonates with the average player, providing a grounded perspective on the world of the game.'),
    ('The Survivor', 'CHARACTER TYPE: The Survivor - Overcomes great obstacles, often emerging stronger from their trials. Their resilience is a key part of their character.'),
    ('The Tyrant', 'CHARACTER TYPE: The Tyrant - A ruler or leader who uses power oppressively or unjustly. Often serves as an antagonist challenging the heros morals.'),
    ('The Shadow', 'CHARACTER TYPE: The Shadow - Represents the darker, often repressed elements of the heros own psyche. Can be an actual nemesis or an internal struggle.'),
    ('The Guardian', 'CHARACTER TYPE: The Guardian - Protects a particular person or treasure, challenging the heros progress but also helping to prepare them for greater challenges ahead.'),
    ('The Artificial Intelligence', 'CHARACTER TYPE: The Artificial Intelligence - Often found in sci-fi or futuristic settings, these characters challenge our understanding of consciousness, existence, and ethics.'),
    ('The Fallen Hero', 'CHARACTER TYPE: The Fallen Hero - A hero who has lost their way, providing narratives on redemption, corruption, or the consequences of power.'),
    ('The Prodigy', 'CHARACTER TYPE: The Prodigy - Exceptionally talented in a specific area, often young or inexperienced in other aspects of life. Their development can challenge traditional norms and expectations.'),
    ('The Martyr', 'CHARACTER TYPE: The Martyr - Sacrifices their own well-being for the sake of others or a cause, often highlighting themes of selflessness and the impact of personal sacrifice.'),
    ('The Rogue', 'CHARACTER TYPE: The Rogue - A charming rule-breaker who operates on the fringes of society. Their flexibility and moral ambiguity can drive complex plot developments.'),
    ('The Misfit', 'CHARACTER TYPE: The Misfit - Doesnt fit into the norms of their society due to an unusual background, appearance, or behavior. Their journey often involves finding acceptance or transforming their environment.'),
    ('The Cynic', 'CHARACTER TYPE: The Cynic - Skeptical of everyone\'s motives and often pessimistic about outcomes, providing a counterpoint to more idealistic characters.'),
    ('The Loner', 'CHARACTER TYPE: The Loner - Prefers solitude and may have difficulty working with others, often providing a deeper dive into themes of isolation and independence.'),
    ('The Paragon', 'CHARACTER TYPE: The Paragon - Represents the ideal standards of a community; their perfection can drive others to aspire or despair, depending on the narratives direction.'),
    ('The Foreigner', 'CHARACTER TYPE: The Foreigner - Comes from another culture or world, providing a fresh perspective on the established norms of the games setting and potentially challenging them.'),
    ('The Underdog', 'CHARACTER TYPE: The Underdog - Lacks traditional advantages and seems destined to fail, making their efforts to succeed more heroic and engaging.'),
    ('The Mentor turned Antagonist', 'CHARACTER TYPE: The Mentor turned Antagonist - Starts as a guiding force for the hero but becomes an adversary, raising questions about trust and betrayal.'),
    ('The Double Agent', 'CHARACTER TYPE: The Double Agent - Operates secretly for two opposing forces, creating complex layers of loyalty and deception in the narrative.'),
    ('The Beast', 'CHARACTER TYPE: The Beast - Not fully human or traditional character, possibly an animal or monster, whose story explores themes of nature, instinct, and civilization.'),
    ('The Healer', 'CHARACTER TYPE: The Healer - Provides physical or emotional healing, crucial in supporting other characters but may face their own moral dilemmas about whom to save.'),
    ('The Pacifist', 'CHARACTER TYPE: The Pacifist - Avoids conflict and seeks peaceful solutions, challenging more aggressive characters and methods.'),
    ('The Zealot', 'CHARACTER TYPE: The Zealot - Has intense beliefs and is willing to go to extremes for their cause, often presenting challenges in terms of alliances and ethical decisions.'),
    ('The Visionary', 'CHARACTER TYPE: The Visionary - Sees a different future and strives to make it a reality, often driving innovation or conflict within the story.'),
    ('The Gambler', 'CHARACTER TYPE: The Gambler - Relies on luck and risk-taking, often providing a wildcard element in strategic situations.'),
    ('The Scholar', 'CHARACTER TYPE: The Scholar - Values knowledge above all else, often contributing critical information or skills at crucial moments.'),
    ('The Drifter', 'CHARACTER TYPE: The Drifter - Moves from place to place, often carrying news, wisdom, or ambiguous intentions, and typically lacks strong ties to any community.'),
    ('The Revolutionary', 'CHARACTER TYPE: The Revolutionary - Committed to radical change, challenging established systems and often becoming a leader in conflict.'),
    ('The Reluctant Hero', 'CHARACTER TYPE: The Reluctant Hero - Unwillingly drawn into the events of the story, their growth into their role explores themes of duty, fate, and free will.'),
    ('The Trickster God', 'CHARACTER TYPE: The Trickster God - A deity or similar powerful being who manipulates events for amusement or their own agenda, adding unpredictability to the narrative.'),
    ('The Recluse', 'CHARACTER TYPE: The Recluse - Lives apart from society voluntarily, often holding secret knowledge or having survived an ordeal that sets them apart.'),
    ('The Amnesiac', 'CHARACTER TYPE: The Amnesiac - Lacks memories of their past, creating a narrative filled with discovery and potential for unexpected revelations about themselves and others.'),
    ('The Puppet Master', 'CHARACTER TYPE: The Puppet Master - Manipulates others from behind the scenes, often serving as a hidden antagonist whose full impact is revealed over time.'),
    ('The Avenger', 'CHARACTER TYPE: The Avenger - Driven by the desire to exact revenge, motivated by deeply personal reasons or past injustices.'),
    ('The Savior', 'CHARACTER TYPE: The Savior - Often plays a crucial role in rescuing or assisting others during pivotal moments, influencing paths and choices in the story.'),
    ('The Wanderer', 'CHARACTER TYPE: The Wanderer - Characterized by extensive travel experience, offering unique perspectives and aid based on a broad knowledge of different cultures and places.'),
    ('The Outlaw', 'CHARACTER TYPE: The Outlaw - Operates outside the accepted societal norms, presenting alternative views on law, morality, and society.'),
    ('The Informer', 'CHARACTER TYPE: The Informer - Supplies essential information or insights, which can influence decisions or understanding of events and characters in the narrative.'),
    ('The Prophet', 'CHARACTER TYPE: The Prophet - Provides guidance through prophecies or foresight, influencing the narratives direction and character choices.'),
    ('The Usurper', 'CHARACTER TYPE: The Usurper - Ambitious and power-seeking, challenging existing authorities or attempting to overthrow established positions.'),
    ('The Mediator', 'CHARACTER TYPE: The Mediator - Facilitates dialogue and resolution in conflicts, influencing relationships and outcomes through negotiation.'),
    ('The Challenger', 'CHARACTER TYPE: The Challenger - Presents tests and trials to others, fostering growth, learning, and development through challenges.'),
    ('The Deserter', 'CHARACTER TYPE: The Deserter - Leaves or abandons a group or cause, often during critical moments, affecting the dynamics and morale of those involved.'),
    ('The Penitent', 'CHARACTER TYPE: The Penitent - Seeks redemption or atonement for past actions, impacting relationships and story arcs with their journey towards forgiveness.'),
    ('The Oracle', 'CHARACTER TYPE: The Oracle - Holds deep knowledge or prophetic abilities, guiding others with insights that shape their understanding and decisions.'),
    ('The Ghost', 'CHARACTER TYPE: The Ghost - A spectral presence that influences the story through unresolved past issues, memories, or moral lessons.'),
]


CHARACTER_TRAITS_CHOICES = [
    ('Brave', 'CHARACTER TRAIT: Brave - Faces danger or adversity courageously.'),
    ('Cunning', 'CHARACTER TRAIT: Cunning - Skilled in or inclined to deception and manipulation.'),
    ('Deceitful', 'CHARACTER TRAIT: Deceitful - Skilled in or inclined to deception and manipulation.'),
    ('Brave', 'CHARACTER TRAIT: Brave - Faces danger or adversity courageously.'),
    ('Cautious', 'CHARACTER TRAIT: Cautious - Takes care to avoid mistakes or danger.'),
    ('Charismatic', 'CHARACTER TRAIT: Charismatic - Has a compelling charm or appeal that can inspire or captivate others.'),
    ('Curious', 'CHARACTER TRAIT: Curious - Has a strong desire to learn or know something.'),
    ('Deceptive', 'CHARACTER TRAIT: Deceptive - Skilled in or inclined to deception and manipulation.'),
    ('Empathetic', 'CHARACTER TRAIT: Empathetic - Has the ability to understand and share the feelings of another.'),
    ('Fierce', 'CHARACTER TRAIT: Fierce - Shows a heartfelt and powerful intensity.'),
    ('Generous', 'CHARACTER TRAIT: Generous - Shows a readiness to give more of something than is strictly necessary or expected.'),
    ('Honest', 'CHARACTER TRAIT: Honest - Free of deceit; truthful and sincere.'),
    ('Impulsive', 'CHARACTER TRAIT: Impulsive - Acts or done without forethought, spontaneous.'),
    ('Intelligent', 'CHARACTER TRAIT: Intelligent - Has the ability to acquire and apply knowledge and skills.'),
    ('Jealous', 'CHARACTER TRAIT: Jealous - Envious of someone else\'s achievements or advantages.'),
    ('Loyal', 'CHARACTER TRAIT: Loyal - Shows firm and constant support or allegiance to a person or institution.'),
    ('Mysterious', 'CHARACTER TRAIT: Mysterious - Difficult or impossible to understand, explain, or identify.'),
    ('Narcissistic', 'CHARACTER TRAIT: Narcissistic - Having an excessive interest in or admiration of oneself and one\'s physical appearance.'),
    ('Obsessive', 'CHARACTER TRAIT: Obsessive - Fills the mind continually, intrusively, and to a troubling extent.'),
    ('Optimistic', 'CHARACTER TRAIT: Optimistic - Hopeful and confident about the future.'),
    ('Pessimistic', 'CHARACTER TRAIT: Pessimistic - Tends to see the worst aspect of things or believe that the worst will happen.'),
    ('Pragmatic', 'CHARACTER TRAIT: Pragmatic - Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.'),
    ('Rebellious', 'CHARACTER TRAIT: Rebellious - Showing a desire to resist authority, control, or convention.'),
    ('Resilient', 'CHARACTER TRAIT: Resilient - Able to withstand or recover quickly from difficult conditions.'),
    ('Ruthless', 'CHARACTER TRAIT: Ruthless - Having or showing no pity or compassion for others.'),
    ('Sarcastic', 'CHARACTER TRAIT: Sarcastic - Marked by or given to using irony to mock or convey contempt.'),
    ('Skeptical', 'CHARACTER TRAIT: Skeptical - Not easily convinced; having doubts or reservations.'),
    ('Strategic', 'CHARACTER TRAIT: Strategic - Carefully designed or planned to serve a particular purpose or advantage.'),
    ('Taciturn', 'CHARACTER TRAIT: Taciturn - Reserved or uncommunicative in speech; saying little.'),
    ('Vain', 'CHARACTER TRAIT: Vain - Having or showing an excessively high opinion of one\'s appearance, abilities, or worth.'),
    ('Wise', 'CHARACTER TRAIT: Wise - Having or showing experience, knowledge, and good judgment.'),
    ('Witty', 'CHARACTER TRAIT: Witty - Showing or characterized by quick and inventive verbal humor.'),
    ('Zealous', 'CHARACTER TRAIT: Zealous - Having or showing zeal, passion or enthusiasm.'),
    ('Adventurous', 'CHARACTER TRAIT: Adventurous - Willing to take risks or try out new methods, ideas, or experiences.'),
    ('Analytical', 'CHARACTER TRAIT: Analytical - Skilled in thinking critically and logically, with a strong focus on solving complex problems.'),
    ('Apathetic', 'CHARACTER TRAIT: Apathetic - Showing or feeling no interest, enthusiasm, or concern.'),
    ('Artistic', 'CHARACTER TRAIT: Artistic - Having natural creative skill or appreciation for the arts.'),
    ('Cynical', 'CHARACTER TRAIT: Cynical - Distrusting or disparaging the motives of others; often skeptical of whether people have good intentions.'),
    ('Diplomatic', 'CHARACTER TRAIT: Diplomatic - Able to deal with people in a sensitive and effective way, often smoothing over conflicts or negotiating successfully.'),
    ('Eccentric', 'CHARACTER TRAIT: Eccentric - Unconventional and slightly strange in behavior or personality.'),
    ('Frugal', 'CHARACTER TRAIT: Frugal - Sparing or economical with regard to money or food.'),
    ('Gullible', 'CHARACTER TRAIT: Gullible - Easily persuaded to believe something, often due to naivety.'),
    ('Heroic', 'CHARACTER TRAIT: Heroic - Displaying heroism or having characteristics of a hero.'),
    ('Idealistic', 'CHARACTER TRAIT: Idealistic - Characterized by idealism, unrealistically aiming for perfection.'),
    ('Innovative', 'CHARACTER TRAIT: Innovative - Featuring new methods; advanced and original.'),
    ('Intuitive', 'CHARACTER TRAIT: Intuitive - Using or based on what one feels to be true even without conscious reasoning.'),
    ('Melancholic', 'CHARACTER TRAIT: Melancholic - Having a feeling of pensive sadness, typically with no obvious cause.'),
    ('Nurturing', 'CHARACTER TRAIT: Nurturing - Caring for and encouraging the growth or development of someone or something.'),
    ('Paranoid', 'CHARACTER TRAIT: Paranoid - Unreasonably or obsessively anxious, suspicious, or mistrustful.'),
    ('Patient', 'CHARACTER TRAIT: Patient - Able to accept or tolerate delays, problems, or suffering without becoming annoyed or anxious.'),
    ('Persistent', 'CHARACTER TRAIT: Persistent - Firmly continuing in a course of action in spite of difficulty or opposition.'),
    ('Pioneering', 'CHARACTER TRAIT: Pioneering - Involving new ideas or methods.'),
    ('Proactive', 'CHARACTER TRAIT: Proactive - Creating or controlling a situation by causing something to happen rather than responding to it after it has happened.'),
    ('Rational', 'CHARACTER TRAIT: Rational - Based on or in accordance with reason or logic.'),
    ('Reflective', 'CHARACTER TRAIT: Reflective - Providing a reflection; capable of reflecting light or other radiation.'),
    ('Relentless', 'CHARACTER TRAIT: Relentless - Oppressively constant; determined.'),
    ('Reserved', 'CHARACTER TRAIT: Reserved - Slow to reveal emotion or opinions.'),
    ('Resourceful', 'CHARACTER TRAIT: Resourceful - Having the ability to find quick and clever ways to overcome difficulties.'),
    ('Sincere', 'CHARACTER TRAIT: Sincere - Free from pretense or deceit; proceeding from genuine feelings.'),
    ('Stoic', 'CHARACTER TRAIT: Stoic - Enduring pain and hardship without showing one\'s feelings or complaining.'),
    ('Sympathetic', 'CHARACTER TRAIT: Sympathetic - Feeling, showing, or expressing sympathy.'),
    ('Temperamental', 'CHARACTER TRAIT: Temperamental - Liable to unreasonable changes of mood.'),
    ('Vigilant', 'CHARACTER TRAIT: Vigilant - Keeping careful watch for possible danger or difficulties.'),
    ('Assertive', 'CHARACTER TRAIT: Assertive - Confident and forceful in expressing one’s opinions or desires.'),
    ('Benevolent', 'CHARACTER TRAIT: Benevolent - Well-meaning and kindly, often showing charity and goodwill towards others.'),
    ('Calculating', 'CHARACTER TRAIT: Calculating - Acting in a scheming and ruthlessly determined way.'),
    ('Charming', 'CHARACTER TRAIT: Charming - Pleasant or attractive, often using this trait to influence or persuade others.'),
    ('Compassionate', 'CHARACTER TRAIT: Compassionate - Feeling or showing sympathy and concern for others, often motivating altruistic actions.'),
    ('Courageous', 'CHARACTER TRAIT: Courageous - Not deterred by danger or pain; brave.'),
    ('Detached', 'CHARACTER TRAIT: Detached - Aloof and objective, often not influenced by emotions or personal involvement.'),
    ('Disciplined', 'CHARACTER TRAIT: Disciplined - Showing a controlled form of behavior or way of working.'),
    ('Dogmatic', 'CHARACTER TRAIT: Dogmatic - Inclined to lay down principles as incontrovertibly true, without consideration of evidence or the opinions of others.'),
    ('Enigmatic', 'CHARACTER TRAIT: Enigmatic - Difficult to interpret or understand; mysterious.'),
    ('Exuberant', 'CHARACTER TRAIT: Exuberant - Filled with or characterized by a lively energy and excitement.'),
    ('Faithful', 'CHARACTER TRAIT: Faithful - Remaining loyal and steadfast, in adherence to promises or in allegiance to a cause or person.'),
    ('Gracious', 'CHARACTER TRAIT: Gracious - Courteous, kind, and pleasant, often despite circumstances that might warrant otherwise.'),
    ('Impartial', 'CHARACTER TRAIT: Impartial - Treating all rivals or disputants equally; fair and just.'),
    ('Impetuous', 'CHARACTER TRAIT: Impetuous - Acting or done quickly and without thought or care; moved by sudden, strong emotions.'),
    ('Industrious', 'CHARACTER TRAIT: Industrious - Diligent and hard-working.'),
    ('Jovial', 'CHARACTER TRAIT: Jovial - Cheerful and friendly.'),
    ('Judicious', 'CHARACTER TRAIT: Judicious - Having, showing, or done with good judgment or sense.'),
    ('Meticulous', 'CHARACTER TRAIT: Meticulous - Showing great attention to detail; very careful and precise.'),
    ('Mischievous', 'CHARACTER TRAIT: Mischievous - Causing or showing a fondness for causing trouble in a playful way.'),
    ('Noble', 'CHARACTER TRAIT: Noble - Having or showing fine personal qualities or high moral principles.'),
    ('Oblivious', 'CHARACTER TRAIT: Oblivious - Not aware of or concerned about what is happening around one.'),
    ('Passionate', 'CHARACTER TRAIT: Passionate - Showing or caused by strong feelings or a strong belief.'),
    ('Pensive', 'CHARACTER TRAIT: Pensive - Engaged in, involving, or reflecting deep or serious thought.'),
    ('Prudent', 'CHARACTER TRAIT: Prudent - Acting with or showing care and thought for the future.'),
    ('Quirky', 'CHARACTER TRAIT: Quirky - Characterized by peculiar or unexpected traits.'),
    ('Resolute', 'CHARACTER TRAIT: Resolute - Admirably purposeful, determined, and unwavering.'),
    ('Savvy', 'CHARACTER TRAIT: Savvy - Shrewdness and practical knowledge, especially in politics or business.'),
    ('Spontaneous', 'CHARACTER TRAIT: Spontaneous - Performed or occurring as a result of a sudden inner impulse or inclination without premeditation.'),
    ('Tactful', 'CHARACTER TRAIT: Tactful - Having or showing tact, the ability to do or say things without offending or upsetting other people.'),
    ('Tenacious', 'CHARACTER TRAIT: Tenacious - Tending to keep a firm hold of something; clinging or adhering closely.'),
    ('Unassuming', 'CHARACTER TRAIT: Unassuming - Not pretentious or arrogant; modest.'),
    ('Vindictive', 'CHARACTER TRAIT: Vindictive - Having or showing a strong or unreasoning desire for revenge.'),
    ('Wary', 'CHARACTER TRAIT: Wary - Feeling or showing caution about possible dangers or problems.'),
    ('Whimsical', 'CHARACTER TRAIT: Whimsical - Playfully quaint or fanciful, especially in an appealing and amusing way.'),
    ('Zealous', 'CHARACTER TRAIT: Zealous - A person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.'),
]


CHARACTER_RELATIONSHIP_CHOICES = [
    ('Ally', 'CHARACTER RELATIONSHIP: Ally - A character who actively cooperates with the protagonist or player character to achieve shared goals.'),
    ('Rival', 'CHARACTER RELATIONSHIP: Rival - A character who competes against the protagonist in a personal way, often pushing both to better themselves.'),
    ('Enemy', 'CHARACTER RELATIONSHIP: Enemy - A character who opposes the protagonist, creating conflict and challenges that drive the narrative.'),
    ('Friend', 'CHARACTER RELATIONSHIP: Friend - A character who supports and cares for the protagonist, offering companionship and assistance.'),
    ('Mentor', 'CHARACTER RELATIONSHIP: Mentor - An experienced advisor who teaches and guides the protagonist, providing wisdom and resources.'),
    ('Family', 'CHARACTER RELATIONSHIP: Family - A character connected by blood or marriage, influencing the protagonist through familial bonds and obligations.'),
    ('Adversary', 'CHARACTER RELATIONSHIP: Adversary - A character who opposes the protagonist, creating conflict and challenges that drive the narrative.'),
    ('Sidekick', 'CHARACTER RELATIONSHIP: Sidekick - A loyal companion who often provides help or comic relief, while also having their own depth and development.'),
    ('Comrade', 'CHARACTER RELATIONSHIP: Comrade - A fellow soldier or warrior who fights alongside the protagonist, sharing the dangers and burdens of battle.'),
    ('Protector', 'CHARACTER RELATIONSHIP: Protector - A character who safeguards the protagonist from harm, often acting as a guardian or shield.'),
    ('Servant', 'CHARACTER RELATIONSHIP: Servant - Someone who serves the protagonist due to duty, loyalty, or employment, often privy to personal aspects of the protagonist’s life.'),
    ('Business Partner', 'CHARACTER RELATIONSHIP: Business Partner - A character linked by financial or entrepreneurial ventures, impacting the protagonist’s professional and personal life.'),
    ('Teacher', 'CHARACTER RELATIONSHIP: Teacher - A character who imparts knowledge or skills, influencing the protagonist’s abilities and choices.'),
    ('Nemesis', 'CHARACTER RELATIONSHIP: Nemesis - A formidable opponent specifically designed to be the protagonist’s chief antagonist, often mirroring their traits or philosophy.'),
    ('Betrayal', 'CHARACTER RELATIONSHIP: Betrayal - A character who deceives or turns against the protagonist, profoundly affecting the emotional tone and direction of the story.'),
    ('Unlikely Friend', 'CHARACTER RELATIONSHIP: Unlikely Friend - A character from a different background or species who forms an unexpected bond with the protagonist, enriching the narrative.'),
    ('Old Friend', 'CHARACTER RELATIONSHIP: Old Friend - A character with a longstanding relationship with the protagonist, offering historical depth and emotional resonance.'),
    ('Enemy to Lover', 'CHARACTER RELATIONSHIP: Enemy to Lover - A character who transitions from being antagonistic to romantically involved with the protagonist, adding complexity to the relationship.'),
    ('Caretaker', 'CHARACTER RELATIONSHIP: Caretaker - Someone who tends to the protagonist during times of need, providing physical or emotional care.'),
    ('Double Agent', 'CHARACTER RELATIONSHIP: Double Agent - A character with unclear loyalties, whose actions directly impact the protagonist’s trust and strategic decisions.'),
    ('Sibling', 'CHARACTER RELATIONSHIP: Sibling - A brother or sister who shares a personal history with the protagonist, affecting their emotional and practical decisions.'),
    ('Blood Enemy', 'CHARACTER RELATIONSHIP: Blood Enemy - A character whose enmity is based on deep-seated, often familial, hatred, driving intense narrative conflicts.'),
    ('Forgotten Friend', 'CHARACTER RELATIONSHIP: Forgotten Friend - A character from the protagonist’s past who re-emerges, bringing up old memories and unresolved issues.'),
    ('Guardian Angel', 'CHARACTER RELATIONSHIP: Guardian Angel - A mysterious or supernatural figure who watches over the protagonist, subtly influencing their journey.'),
    ('Soulmate', 'CHARACTER RELATIONSHIP: Soulmate - A character who is portrayed as having a profound, often destined connection with the protagonist.'),
    ('Kindred Spirit', 'CHARACTER RELATIONSHIP: Kindred Spirit - A character who shares similar beliefs, motivations, or experiences with the protagonist, fostering a deep mutual understanding.'),
    ('Conspirator', 'CHARACTER RELATIONSHIP: Conspirator - A character who secretly plots with the protagonist, engaging in schemes or plans that drive the plot.'),
    ('Arch Enemy', 'CHARACTER RELATIONSHIP: Arch Enemy - The ultimate personal antagonist, whose goals are diametrically opposed to the protagonist’s, often leading to epic showdowns.'),
    ('Confidant', 'CHARACTER RELATIONSHIP: Confidant - A trusted character who the protagonist can confide in and who often provides emotional support or strategic advice.'),
    ('Foe', 'CHARACTER RELATIONSHIP: Foe - A personal enemy who opposes the protagonist but isn\'t necessarily involved in the main conflict, providing side challenges or personal growth opportunities.'),
    ('Heir', 'CHARACTER RELATIONSHIP: Heir - A character, often younger, designated to carry on the protagonist’s legacy or family lineage, shaping future storylines or generational narratives.'),
    ('Disciple', 'CHARACTER RELATIONSHIP: Disciple - A follower or student who looks up to the protagonist as a leader or teacher, reflecting the protagonist\'s values and methods.'),
    ('Benefactor', 'CHARACTER RELATIONSHIP: Benefactor - A character who provides support, often financially or through resources, which can significantly influence the protagonist\'s capabilities and options.'),
    ('Blackmailer', 'CHARACTER RELATIONSHIP: Blackmailer - A character who manipulates the protagonist by threatening to reveal sensitive information, creating tension and moral dilemmas.'),
]


CHARACTER_BACKSTORY_CHOICES = [
    ('Orphaned at a Young Age', 'CHARACTER BACKSTORY: Orphaned at a Young Age - Grew up without parents, leading to a strong sense of independence and survival skills, or possibly a longing for true family connections.'),
    ('Former Royalty', 'CHARACTER BACKSTORY: Former Royalty - Dethroned or in exile, struggling with a loss of status and power, and perhaps seeking to reclaim their rightful place or adjust to a new life.'),
    ('Retired Soldier', 'CHARACTER BACKSTORY: Retired Soldier - Experienced in combat but haunted by past wars, now seeking peace or redemption, possibly being pulled back for one last mission.'),
    ('Crime Victim', 'CHARACTER BACKSTORY: Crime Victim - Suffered a great personal loss due to crime, which fuels a quest for justice or revenge against the criminal underworld.'),
    ('Amnesiac', 'CHARACTER BACKSTORY: Amnesiac - Wakes up with no memory of their past, driving a quest for self-discovery that uncovers dark secrets or unexpected truths.'),
    ('Child Prodigy', 'CHARACTER BACKSTORY: Child Prodigy - Born with exceptional talents, which led to an unconventional upbringing, now navigating the challenges of expectations and self-discovery.'),
    ('Survivor of a Disaster', 'CHARACTER BACKSTORY: Survivor of a Disaster - The sole or one of few survivors of a catastrophe, struggling with survivor’s guilt and the challenges of rebuilding life.'),
    ('Former Thief', 'CHARACTER BACKSTORY: Former Thief - Skilled in stealth and deception, trying to leave a life of crime behind but finding old skills still useful in new, more noble pursuits.'),
    ('Lost Heir', 'CHARACTER BACKSTORY: Lost Heir - The missing heir to a powerful dynasty, unaware of true heritage or thrust into a struggle for power they never wanted.'),
    ('Alien in a Foreign Land', 'CHARACTER BACKSTORY: Alien in a Foreign Land - From another world or culture, trying to fit in or fulfill a mission in a strange new place, dealing with cultural misunderstandings.'),
    ('Cursed Individual', 'CHARACTER BACKSTORY: Cursed Individual - Afflicted by a curse or supernatural condition, seeking a cure or learning to harness the power it grants for good or ill.'),
    ('Exiled for a Crime', 'CHARACTER BACKSTORY: Exiled for a Crime - Banished after being framed or committing a crime, now seeking to clear their name or adapt to life on the fringes of society.'),
    ('Secret Organization Member', 'CHARACTER BACKSTORY: Secret Organization Member - Part of a clandestine group with mysterious goals, torn between loyalty to the group and personal moral dilemmas.'),
    ('Disgraced Leader', 'CHARACTER BACKSTORY: Disgraced Leader - Once respected in their community or field, now disgraced and seeking redemption or a chance to prove their worth anew.'),
    ('Warrior in Training', 'CHARACTER BACKSTORY: Warrior in Training - Young and relatively inexperienced, eager to prove themselves in a conflict or competition that is central to their culture or family.'),
    ('Scholar of the Arcane', 'CHARACTER BACKSTORY: Scholar of the Arcane - Devoted to studying magic or ancient technology, whose research leads them into adventures or attracts dangerous attention.'),
    ('Inventor with a Key Creation', 'CHARACTER BACKSTORY: Inventor with a Key Creation - Created something powerful or valuable and now must protect it from those who would use it for harm.'),
    ('Wanderer with No Home', 'CHARACTER BACKSTORY: Wanderer with No Home - Continuously travels from place to place, driven by wanderlust, a mission, or as a way to escape from past troubles.'),
    ('Reformed Villain', 'CHARACTER BACKSTORY: Reformed Villain - Once worked against what they now see as the greater good, seeking to make amends and find redemption.'),
    ('Visionary with a Dream', 'CHARACTER BACKSTORY: Visionary with a Dream - Sees a different future and is dedicated to making it a reality, whether it’s starting a revolution, building a utopia, or inventing transformative technology.'),
    ('Mercenary with a Code', 'CHARACTER BACKSTORY: Mercenary with a Code - Hired fighter who follows a strict personal code, which might clash with their assignments or lead to unexpected alliances.'),
    ('Spiritual Guide', 'CHARACTER BACKSTORY: Spiritual Guide - Has a deep spiritual connection and serves as a mentor or healer, guiding others through conflicts that are not just physical but also metaphysical.'),
    ('Fallen Hero', 'CHARACTER BACKSTORY: Fallen Hero - Once celebrated for heroic deeds but fell from grace due to a mistake or misjudgment, now seeking a way back to the light or further into darkness.'),
    ('Secret Keeper', 'CHARACTER BACKSTORY: Secret Keeper - Holds a significant secret that affects their actions and relationships, adding layers of intrigue and responsibility to their role.'),
    ('Adventurer Turned Reluctant Hero', 'CHARACTER BACKSTORY: Adventurer Turned Reluctant Hero - Started as someone seeking thrills or treasure, but is now pulled into significant events that require true heroism.'),
    ('Escaped Convict', 'CHARACTER BACKSTORY: Escaped Convict - Broke out of imprisonment and is either seeking to prove their innocence or trying to start anew, dodging authorities or former enemies along the way.'),
    ('Last of Their Kind', 'CHARACTER BACKSTORY: Last of Their Kind - The sole survivor of a race or civilization, burdened with the legacy and possibly the preservation of their culture or species.'),
    ('Former Monarch Advisor', 'CHARACTER BACKSTORY: Former Monarch Advisor - Once an advisor to a powerful ruler, now on the run or in hiding after a political coup, possessing secrets that could alter the balance of power.'),
    ('Street Urchin Turned Rogue', 'CHARACTER BACKSTORY: Street Urchin Turned Rogue - Grew up on the streets, learned to survive by their wits and agility, and now uses those skills for greater or more noble causes.'),
    ('Rebel Leader', 'CHARACTER BACKSTORY: Rebel Leader - Heads a resistance against a tyrannical regime, driven by personal loss or a deep-seated belief in freedom and justice.'),
    ('Time Traveler', 'CHARACTER BACKSTORY: Time Traveler - From another time period, either stranded in the present or on a mission from the future, grappling with temporal paradoxes and cultural differences.'),
    ('Experimental Subject', 'CHARACTER BACKSTORY: Experimental Subject - Part of a scientific or magical experiment, either imbued with unique powers or cursed, and dealing with the consequences.'),
    ('Ancient Warrior Reawakened', 'CHARACTER BACKSTORY: Ancient Warrior Reawakened - From a long-gone era, awakened in the modern world and struggling to adapt to new technologies and customs while facing old enemies.'),
    ('Artificial Intelligence', 'CHARACTER BACKSTORY: Artificial Intelligence - Gained sentience and is exploring what it means to be alive, dealing with existential questions and threats from those who see it as a danger.'),
    ('Diplomat in a War-Torn Land', 'CHARACTER BACKSTORY: Diplomat in a War-Torn Land - Trying to negotiate peace or at least survival in a region torn by conflict, balancing complex alliances and moral compromises.'),
    ('Healer in a Plague-Ridden Land', 'CHARACTER BACKSTORY: Healer in a Plague-Ridden Land - Possesses unique abilities or knowledge to cure diseases, but faces suspicion and fear from those they try to help.'),
    ('Smuggler with a Golden Heart', 'CHARACTER BACKSTORY: Smuggler with a Golden Heart - Moves goods or people illegally, but follows a strict ethical code, often helping those in need against oppressive systems.'),
    ('Bounty Hunter with a Secret', 'CHARACTER BACKSTORY: Bounty Hunter with a Secret - Tracks down fugitives for money, but is secretly helping some escape from unjust fates.'),
    ('Defector from a Powerful Faction', 'CHARACTER BACKSTORY: Defector from a Powerful Faction - Once part of a dominant group or ideology, now turned against them and facing repercussions.'),
    ('Scholar of Lost History', 'CHARACTER BACKSTORY: Scholar of Lost History - Seeks ancient truths that have been suppressed or forgotten, often finding themselves in danger from those who want the past to remain hidden.'),
    ('Survivor of a Failed Expedition', 'CHARACTER BACKSTORY: Survivor of a Failed Expedition - The only one to return from a disastrous journey, haunted by failure and the loss of friends, but possibly holding key discoveries.'),
    ('Child of Two Worlds', 'CHARACTER BACKSTORY: Child of Two Worlds - Born to parents from opposing sides of a cultural or racial divide, embodying the potential for unity or conflict between their communities.'),
    ('Celebrity Athlete in Decline', 'CHARACTER BACKSTORY: Celebrity Athlete in Decline - Once at the top of their sport, now facing the twilight of their career and trying to find a new purpose.'),
    ('Disowned Noble', 'CHARACTER BACKSTORY: Disowned Noble - Cast out from a noble family due to a scandal or disagreement, struggling with identity and survival without the accustomed luxury and power.'),
    ('Veteran of a Lost War', 'CHARACTER BACKSTORY: Veteran of a Lost War - Returned from a conflict that ended in defeat, dealing with the memories and trying to find peace in a world that has moved on.'),
    ('Pirate Turned Privateer', 'CHARACTER BACKSTORY: Pirate Turned Privateer - Once a feared outlaw of the seas, now operating under a government license, caught between their old comrades and new duties.'),
    ('Wilderness Survivor', 'CHARACTER BACKSTORY: Wilderness Survivor - Lived in the wilderness after a crash or catastrophe, returning to civilization with a unique perspective and unusual skills.'),
    ('Cosmic Wanderer', 'CHARACTER BACKSTORY: Cosmic Wanderer - Travels the galaxy with knowledge or artifacts that many factions desire, constantly on the move to avoid capture.'),
    ('Ghost Haunting Their Killer', 'CHARACTER BACKSTORY: Ghost Haunting Their Killer - A spectral being seeking to bring their murderer to justice or find peace by resolving unfinished business.'),
    ('Dimensional Drifter', 'CHARACTER BACKSTORY: Dimensional Drifter - Inadvertently travels between different realities, seeking a way to return home or make sense of their shifting existence.')
]
