# Generated by Django 4.2.6 on 2024-04-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='collaborators',
        ),
    ]
