# Generated by Django 4.2.6 on 2024-04-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script_generation', '0002_remove_story_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='script',
        ),
        migrations.RemoveField(
            model_name='character',
            name='story',
        ),
        migrations.RemoveField(
            model_name='script',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='script',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='script',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='script',
            name='story_tone',
        ),
        migrations.RemoveField(
            model_name='script',
            name='story_type',
        ),
        migrations.RemoveField(
            model_name='script',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='script',
            name='user',
        ),
        migrations.RemoveField(
            model_name='script',
            name='writing_style',
        ),
        migrations.AddField(
            model_name='relationship',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='script_generation.story'),
        ),
        migrations.CreateModel(
            name='StoryCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_generation.character')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='script_generation.story')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='stories',
            field=models.ManyToManyField(related_name='characters', through='script_generation.StoryCharacter', to='script_generation.story'),
        ),
    ]
