# Generated by Django 4.2.6 on 2024-05-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script_generation', '0003_remove_character_character_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storycharacter',
            name='role',
        ),
        migrations.AddField(
            model_name='character',
            name='character_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_genre',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_pace',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_period',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_setting',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_style',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_tone',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='script',
            name='script_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ScriptCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_generation.character')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_generation.script')),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='characters',
            field=models.ManyToManyField(related_name='scripts', through='script_generation.ScriptCharacter', to='script_generation.character'),
        ),
    ]
