# Generated by Django 4.2.6 on 2024-05-06 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script_generation', '0004_remove_storycharacter_role_character_character_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='GeneratedScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_scripts', to='script_generation.script')),
            ],
        ),
    ]
