# Generated by Django 4.2.6 on 2024-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_generation', '0005_alter_trait_description_generatedscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='index_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
