# Generated by Django 4.2.6 on 2024-05-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_generation', '0006_story_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_context',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
